.PHONY: clean All

All:
	@echo "----------Building project:[ Comm_Line_Util - Debug ]----------"
	@cd "Comm_Line_Util" && "$(MAKE)" -f  "Comm_Line_Util.mk"
clean:
	@echo "----------Cleaning project:[ Comm_Line_Util - Debug ]----------"
	@cd "Comm_Line_Util" && "$(MAKE)" -f  "Comm_Line_Util.mk" clean
